### ISSUE TITLE
AS3 module - tenant_name usage

### ISSUE THREAD

**Issue by nmenant** [F5Networks/tf-bigip-version0.12#24]
https://www.terraform.io/docs/providers/bigip/r/bigip_as3.html
 
Here we specify that there is a mandatory tenant_name parameter:
It is not used and processed in any way (I tested it) – so I guess it’s specific to terraform

In the example supplied on this page, we have the tenant name that is also specified in the as3 declaration. There is a tenant called “as3” specified in the declaration
 
I put a custom tenant_name value as a parameter and used another tenant_name in my declaration. The later one is the one that matters. In this case, Terraform believe that you deal with a Tenant that is not the one specified in the declaration.
 
Why don’t we just extract the tenant name attribute from the declaration ? It would be less prone to errors… What about AS3 declaration that may have multiple tenants in it ?

**Comment by papineni87** [comment]
@nmenant 
we need one state variable to handle terraform state changes, so we have included tenant name as mandatory parameter to handle state changes and it is no where related to AS3 tenant declaration .

Since it looks little bit confusing, we will change the variable name and ask user to provide some arbitrary name which will handle state changes. We will be updating the same in documentation also.

**Comment by focrensh** [comment]
Updates made to vars required for AS3 resource
